### ISSUE TITLE
Initial MKMapView

### ISSUE THREAD

**Issue by katelewis** [942v/Geotify-RW#1]
Hello,

Do you know how to set the initial map view to the user's current location in this app?

**Comment by 942v** [comment]
Hi, 

If you want to zoom in to the user location you should use the MKMapView Delegate:

1) Set the delegate of your MKMapView to point to your VC.

2) implement this method:

``` Objective-C
- (void)mapView:(MKMapView *)mapView didUpdateUserLocation:(MKUserLocation *)userLocation {
    MKCoordinateRegion mapRegion;   
    mapRegion.center = map.userLocation.coordinate;
    mapRegion.span = MKCoordinateSpanMake(0.2, 0.2);
    [map setRegion:mapRegion animated: YES];
}
```
